/* Parsing tree 0*/
if (missing(feature_25) or feature_25 <= 1.2) then do;
    if (missing(feature_25) or feature_25 <= 0.62) then do;
        if (missing(feature_9) or feature_9 <= 1.04) then do;
            if (missing(feature_3) or feature_3 <= 1.62) then do;
                if (missing(feature_13) or feature_13 <= 1.31) then do;
                    treeValue0 = 0.1;
                end;
                else do;
                    treeValue0 = 0.14;
                end;
            end;
            else do;
                treeValue0 = 0.06;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.83) then do;
                treeValue0 = 0.15;
            end;
            else do;
                treeValue0 = 0.11;
            end;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0.87) then do;
            if (missing(feature_26) or feature_26 <= 0.78) then do;
                if (missing(feature_24) or feature_24 <= 0.64) then do;
                    treeValue0 = 0.13;
                end;
                else do;
                    treeValue0 = 0.07;
                end;
            end;
            else do;
                if (missing(feature_25) or feature_25 <= 0.97) then do;
                    if (missing(feature_27) or feature_27 <= 0.9) then do;
                        if (missing(feature_26) or feature_26 <= 0.87) then do;
                            if (missing(feature_27) or feature_27 <= 0.8) then do;
                                treeValue0 = 0.17;
                            end;
                            else do;
                                treeValue0 = 0.1;
                            end;
                        end;
                        else do;
                            treeValue0 = 0.18;
                        end;
                    end;
                    else do;
                        if (missing(feature_3) or feature_3 <= 1.33) then do;
                            treeValue0 = 0.14;
                        end;
                        else do;
                            treeValue0 = 0.09;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0.11;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.86) then do;
                    if (missing(feature_25) or feature_25 <= 0.84) then do;
                        treeValue0 = 0.19;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1.19) then do;
                            treeValue0 = 0.15;
                        end;
                        else do;
                            treeValue0 = 0.06;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0.2;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1.73) then do;
                    if (missing(feature_3) or feature_3 <= 2.62) then do;
                        if (missing(feature_25) or feature_25 <= 0.99) then do;
                            treeValue0 = 0.16;
                        end;
                        else do;
                            treeValue0 = 0.12;
                        end;
                    end;
                    else do;
                        treeValue0 = 0.06;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 1.08) then do;
                        treeValue0 = 0.06;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1.48) then do;
                            treeValue0 = 0.16;
                        end;
                        else do;
                            treeValue0 = 0.07;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1.83) then do;
        if (missing(feature_22) or feature_22 <= 1.05) then do;
            if (missing(feature_27) or feature_27 <= 0.96) then do;
                if (missing(feature_5) or feature_5 <= 0.9) then do;
                    if (missing(feature_9) or feature_9 <= 0.93) then do;
                        treeValue0 = 0.04;
                    end;
                    else do;
                        if (missing(feature_10) or feature_10 <= -0.12) then do;
                            treeValue0 = 0.15;
                        end;
                        else do;
                            treeValue0 = 0.07;
                        end;
                    end;
                end;
                else do;
                    treeValue0 = 0.12;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 0.75) then do;
                    treeValue0 = 0.14;
                end;
                else do;
                    treeValue0 = 0.05;
                end;
            end;
        end;
        else do;
            treeValue0 = 0.12;
        end;
    end;
    else do;
        treeValue0 = 0.06;
    end;
end;

/* Parsing tree 1*/
if (missing(feature_25) or feature_25 <= 1.07) then do;
    if (missing(feature_25) or feature_25 <= 0.67) then do;
        if (missing(feature_9) or feature_9 <= 1.14) then do;
            if (missing(feature_13) or feature_13 <= 1.3) then do;
                if (missing(feature_24) or feature_24 <= 0.72) then do;
                    treeValue1 = -0.01;
                end;
                else do;
                    if (missing(feature_26) or feature_26 <= 0.73) then do;
                        treeValue1 = -0.06;
                    end;
                    else do;
                        if (missing(feature_22) or feature_22 <= 0.82) then do;
                            treeValue1 = 0.0;
                        end;
                        else do;
                            treeValue1 = -0.04;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue1 = 0.01;
            end;
        end;
        else do;
            if (missing(feature_19) or feature_19 <= 1.23) then do;
                treeValue1 = 0.03;
            end;
            else do;
                treeValue1 = -0.04;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.81) then do;
            if (missing(feature_5) or feature_5 <= 0.82) then do;
                if (missing(feature_14) or feature_14 <= 0.81) then do;
                    treeValue1 = -0.04;
                end;
                else do;
                    treeValue1 = 0.0;
                end;
            end;
            else do;
                if (missing(feature_6) or feature_6 <= -0.55) then do;
                    treeValue1 = -0.01;
                end;
                else do;
                    treeValue1 = 0.05;
                end;
            end;
        end;
        else do;
            if (missing(feature_26) or feature_26 <= 1.08) then do;
                if (missing(feature_5) or feature_5 <= 0.87) then do;
                    if (missing(feature_9) or feature_9 <= 1.25) then do;
                        if (missing(feature_3) or feature_3 <= 1.14) then do;
                            if (missing(feature_25) or feature_25 <= 0.98) then do;
                                if (missing(feature_26) or feature_26 <= 0.84) then do;
                                    treeValue1 = 0.01;
                                end;
                                else do;
                                    treeValue1 = 0.05;
                                end;
                            end;
                            else do;
                                treeValue1 = -0.0;
                            end;
                        end;
                        else do;
                            treeValue1 = 0.01;
                        end;
                    end;
                    else do;
                        treeValue1 = 0.07;
                    end;
                end;
                else do;
                    treeValue1 = 0.06;
                end;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 2.45) then do;
                    if (missing(feature_9) or feature_9 <= 1.85) then do;
                        treeValue1 = 0.01;
                    end;
                    else do;
                        treeValue1 = 0.06;
                    end;
                end;
                else do;
                    treeValue1 = -0.07;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1.83) then do;
        if (missing(feature_22) or feature_22 <= 1.04) then do;
            if (missing(feature_22) or feature_22 <= 0.78) then do;
                treeValue1 = 0.0;
            end;
            else do;
                if (missing(feature_24) or feature_24 <= 0.66) then do;
                    treeValue1 = 0.01;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0.98) then do;
                        if (missing(feature_26) or feature_26 <= 0.99) then do;
                            treeValue1 = -0.04;
                        end;
                        else do;
                            treeValue1 = -0.08;
                        end;
                    end;
                    else do;
                        treeValue1 = -0.03;
                    end;
                end;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 1.33) then do;
                if (missing(feature_2) or feature_2 <= 1.09) then do;
                    if (missing(feature_19) or feature_19 <= 1.29) then do;
                        if (missing(feature_3) or feature_3 <= 0.36) then do;
                            treeValue1 = 0.03;
                        end;
                        else do;
                            treeValue1 = -0.04;
                        end;
                    end;
                    else do;
                        treeValue1 = 0.04;
                    end;
                end;
                else do;
                    treeValue1 = 0.04;
                end;
            end;
            else do;
                treeValue1 = 0.03;
            end;
        end;
    end;
    else do;
        treeValue1 = -0.06;
    end;
end;

/* Parsing tree 2*/
if (missing(feature_27) or feature_27 <= 0.9) then do;
    if (missing(feature_26) or feature_26 <= 0.81) then do;
        if (missing(feature_5) or feature_5 <= 0.82) then do;
            if (missing(feature_0) or feature_0 <= 1.65) then do;
                if (missing(feature_9) or feature_9 <= 1.19) then do;
                    treeValue2 = -0.03;
                end;
                else do;
                    treeValue2 = 0.02;
                end;
            end;
            else do;
                treeValue2 = 0.02;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.81) then do;
                if (missing(feature_2) or feature_2 <= -1.51) then do;
                    treeValue2 = -0.05;
                end;
                else do;
                    treeValue2 = 0.03;
                end;
            end;
            else do;
                treeValue2 = -0.03;
            end;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0.9) then do;
            if (missing(feature_22) or feature_22 <= 1.06) then do;
                if (missing(feature_27) or feature_27 <= 0.84) then do;
                    if (missing(feature_26) or feature_26 <= 0.86) then do;
                        treeValue2 = 0.0;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 0.7) then do;
                            treeValue2 = 0.01;
                        end;
                        else do;
                            treeValue2 = 0.05;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_26) or feature_26 <= 0.9) then do;
                        treeValue2 = -0.05;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1.04) then do;
                            treeValue2 = -0.02;
                        end;
                        else do;
                            treeValue2 = 0.04;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue2 = 0.05;
            end;
        end;
        else do;
            treeValue2 = 0.05;
        end;
    end;
end;
else do;
    if (missing(feature_22) or feature_22 <= 1.05) then do;
        if (missing(feature_24) or feature_24 <= 1.08) then do;
            if (missing(feature_27) or feature_27 <= 1.09) then do;
                treeValue2 = -0.05;
            end;
            else do;
                treeValue2 = -0.08;
            end;
        end;
        else do;
            if (missing(feature_22) or feature_22 <= 0.76) then do;
                treeValue2 = 0.03;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 1.63) then do;
                    treeValue2 = -0.01;
                end;
                else do;
                    if (missing(feature_2) or feature_2 <= 0.52) then do;
                        treeValue2 = -0.02;
                    end;
                    else do;
                        treeValue2 = -0.08;
                    end;
                end;
            end;
        end;
    end;
    else do;
        if (missing(feature_27) or feature_27 <= 1.12) then do;
            if (missing(feature_5) or feature_5 <= 1.65) then do;
                if (missing(feature_6) or feature_6 <= -1.82) then do;
                    treeValue2 = -0.06;
                end;
                else do;
                    if (missing(feature_6) or feature_6 <= 1.38) then do;
                        treeValue2 = 0.02;
                    end;
                    else do;
                        treeValue2 = -0.04;
                    end;
                end;
            end;
            else do;
                treeValue2 = 0.08;
            end;
        end;
        else do;
            if (missing(feature_3) or feature_3 <= 2.45) then do;
                if (missing(feature_8) or feature_8 <= 0.0) then do;
                    if (missing(feature_5) or feature_5 <= 1.76) then do;
                        if (missing(feature_23) or feature_23 <= 0.99) then do;
                            treeValue2 = 0.03;
                        end;
                        else do;
                            treeValue2 = -0.02;
                        end;
                    end;
                    else do;
                        treeValue2 = 0.05;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 1.31) then do;
                        if (missing(feature_24) or feature_24 <= 0.81) then do;
                            treeValue2 = 0.03;
                        end;
                        else do;
                            treeValue2 = -0.06;
                        end;
                    end;
                    else do;
                        treeValue2 = -0.0;
                    end;
                end;
            end;
            else do;
                treeValue2 = -0.07;
            end;
        end;
    end;
end;

/* Parsing tree 3*/
if (missing(feature_25) or feature_25 <= 1.25) then do;
    if (missing(feature_25) or feature_25 <= 0.59) then do;
        if (missing(feature_9) or feature_9 <= 1.67) then do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_0) or feature_0 <= 0.96) then do;
                    if (missing(feature_9) or feature_9 <= 0.76) then do;
                        treeValue3 = -0.05;
                    end;
                    else do;
                        if (missing(feature_17) or feature_17 <= 1.25) then do;
                            treeValue3 = -0.02;
                        end;
                        else do;
                            treeValue3 = 0.05;
                        end;
                    end;
                end;
                else do;
                    treeValue3 = 0.0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1.0) then do;
                    treeValue3 = -0.06;
                end;
                else do;
                    treeValue3 = -0.02;
                end;
            end;
        end;
        else do;
            treeValue3 = 0.04;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0.88) then do;
            if (missing(feature_26) or feature_26 <= 0.78) then do;
                if (missing(feature_24) or feature_24 <= 0.64) then do;
                    treeValue3 = 0.01;
                end;
                else do;
                    treeValue3 = -0.04;
                end;
            end;
            else do;
                if (missing(feature_25) or feature_25 <= 0.97) then do;
                    if (missing(feature_27) or feature_27 <= 0.86) then do;
                        treeValue3 = 0.04;
                    end;
                    else do;
                        if (missing(feature_9) or feature_9 <= 1.27) then do;
                            if (missing(feature_1) or feature_1 <= 1.77) then do;
                                treeValue3 = 0.01;
                            end;
                            else do;
                                treeValue3 = -0.07;
                            end;
                        end;
                        else do;
                            treeValue3 = 0.05;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_9) or feature_9 <= 1.04) then do;
                        treeValue3 = -0.03;
                    end;
                    else do;
                        treeValue3 = 0.01;
                    end;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.86) then do;
                    if (missing(feature_25) or feature_25 <= 0.95) then do;
                        treeValue3 = 0.05;
                    end;
                    else do;
                        treeValue3 = -0.01;
                    end;
                end;
                else do;
                    treeValue3 = 0.07;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1.73) then do;
                    if (missing(feature_3) or feature_3 <= 2.03) then do;
                        if (missing(feature_25) or feature_25 <= 0.99) then do;
                            treeValue3 = 0.04;
                        end;
                        else do;
                            treeValue3 = 0.0;
                        end;
                    end;
                    else do;
                        treeValue3 = -0.03;
                    end;
                end;
                else do;
                    if (missing(feature_6) or feature_6 <= 1.13) then do;
                        if (missing(feature_24) or feature_24 <= 1.09) then do;
                            treeValue3 = -0.08;
                        end;
                        else do;
                            treeValue3 = -0.01;
                        end;
                    end;
                    else do;
                        treeValue3 = 0.05;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1.85) then do;
        if (missing(feature_24) or feature_24 <= 1.32) then do;
            if (missing(feature_27) or feature_27 <= 1.02) then do;
                if (missing(feature_15) or feature_15 <= -1.57) then do;
                    treeValue3 = 0.07;
                end;
                else do;
                    if (missing(feature_22) or feature_22 <= 1.11) then do;
                        treeValue3 = -0.04;
                    end;
                    else do;
                        treeValue3 = 0.02;
                    end;
                end;
            end;
            else do;
                treeValue3 = -0.06;
            end;
        end;
        else do;
            if (missing(feature_17) or feature_17 <= 1.68) then do;
                treeValue3 = -0.02;
            end;
            else do;
                treeValue3 = 0.05;
            end;
        end;
    end;
    else do;
        treeValue3 = -0.09;
    end;
end;

/* Parsing tree 4*/
if (missing(feature_25) or feature_25 <= 1.07) then do;
    if (missing(feature_25) or feature_25 <= 0.67) then do;
        if (missing(feature_9) or feature_9 <= 1.14) then do;
            if (missing(feature_27) or feature_27 <= 0.85) then do;
                if (missing(feature_26) or feature_26 <= 0.79) then do;
                    if (missing(feature_22) or feature_22 <= 1.1) then do;
                        if (missing(feature_19) or feature_19 <= -1.17) then do;
                            treeValue4 = 0.01;
                        end;
                        else do;
                            treeValue4 = -0.04;
                        end;
                    end;
                    else do;
                        treeValue4 = 0.04;
                    end;
                end;
                else do;
                    if (missing(feature_13) or feature_13 <= 1.37) then do;
                        treeValue4 = 0.01;
                    end;
                    else do;
                        treeValue4 = 0.09;
                    end;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1.17) then do;
                    if (missing(feature_24) or feature_24 <= 1.04) then do;
                        treeValue4 = -0.07;
                    end;
                    else do;
                        treeValue4 = -0.02;
                    end;
                end;
                else do;
                    treeValue4 = -0.0;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.83) then do;
                treeValue4 = 0.04;
            end;
            else do;
                treeValue4 = -0.0;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.78) then do;
            if (missing(feature_5) or feature_5 <= 0.82) then do;
                treeValue4 = -0.04;
            end;
            else do;
                treeValue4 = 0.03;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.86) then do;
                    if (missing(feature_25) or feature_25 <= 0.84) then do;
                        treeValue4 = 0.05;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1.32) then do;
                            treeValue4 = 0.01;
                        end;
                        else do;
                            treeValue4 = -0.08;
                        end;
                    end;
                end;
                else do;
                    treeValue4 = 0.06;
                end;
            end;
            else do;
                if (missing(feature_3) or feature_3 <= 1.77) then do;
                    if (missing(feature_24) or feature_24 <= 1.18) then do;
                        if (missing(feature_22) or feature_22 <= 1.02) then do;
                            if (missing(feature_24) or feature_24 <= 1.0) then do;
                                treeValue4 = -0.05;
                            end;
                            else do;
                                treeValue4 = 0.02;
                            end;
                        end;
                        else do;
                            treeValue4 = 0.03;
                        end;
                    end;
                    else do;
                        treeValue4 = 0.03;
                    end;
                end;
                else do;
                    treeValue4 = -0.02;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1.83) then do;
        if (missing(feature_22) or feature_22 <= 1.04) then do;
            if (missing(feature_27) or feature_27 <= 1.0) then do;
                if (missing(feature_5) or feature_5 <= 1.19) then do;
                    treeValue4 = -0.03;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0.99) then do;
                        treeValue4 = -0.01;
                    end;
                    else do;
                        treeValue4 = 0.06;
                    end;
                end;
            end;
            else do;
                if (missing(feature_24) or feature_24 <= 1.51) then do;
                    treeValue4 = -0.07;
                end;
                else do;
                    treeValue4 = -0.03;
                end;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 1.33) then do;
                if (missing(feature_2) or feature_2 <= 1.09) then do;
                    if (missing(feature_27) or feature_27 <= 1.16) then do;
                        treeValue4 = -0.0;
                    end;
                    else do;
                        treeValue4 = -0.06;
                    end;
                end;
                else do;
                    treeValue4 = 0.04;
                end;
            end;
            else do;
                treeValue4 = 0.03;
            end;
        end;
    end;
    else do;
        treeValue4 = -0.06;
    end;
end;

/* Parsing tree 5*/
if (missing(feature_25) or feature_25 <= 1.18) then do;
    if (missing(feature_25) or feature_25 <= 0.59) then do;
        if (missing(feature_13) or feature_13 <= 0.94) then do;
            if (missing(feature_0) or feature_0 <= 0.91) then do;
                if (missing(feature_24) or feature_24 <= 0.73) then do;
                    if (missing(feature_22) or feature_22 <= 0.94) then do;
                        treeValue5 = -0.05;
                    end;
                    else do;
                        treeValue5 = 0.02;
                    end;
                end;
                else do;
                    treeValue5 = -0.06;
                end;
            end;
            else do;
                if (missing(feature_9) or feature_9 <= 1.01) then do;
                    if (missing(feature_22) or feature_22 <= 0.9) then do;
                        if (missing(feature_5) or feature_5 <= 1.1) then do;
                            treeValue5 = 0.01;
                        end;
                        else do;
                            treeValue5 = -0.07;
                        end;
                    end;
                    else do;
                        treeValue5 = -0.04;
                    end;
                end;
                else do;
                    treeValue5 = 0.03;
                end;
            end;
        end;
        else do;
            treeValue5 = -0.0;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.78) then do;
            if (missing(feature_5) or feature_5 <= 0.8) then do;
                if (missing(feature_24) or feature_24 <= 0.72) then do;
                    treeValue5 = -0.01;
                end;
                else do;
                    treeValue5 = -0.05;
                end;
            end;
            else do;
                treeValue5 = 0.02;
            end;
        end;
        else do;
            if (missing(feature_25) or feature_25 <= 0.98) then do;
                if (missing(feature_3) or feature_3 <= 1.55) then do;
                    if (missing(feature_0) or feature_0 <= 1.4) then do;
                        if (missing(feature_5) or feature_5 <= 0.88) then do;
                            if (missing(feature_25) or feature_25 <= 0.75) then do;
                                if (missing(feature_24) or feature_24 <= 0.75) then do;
                                    treeValue5 = 0.07;
                                end;
                                else do;
                                    treeValue5 = 0.0;
                                end;
                            end;
                            else do;
                                treeValue5 = 0.04;
                            end;
                        end;
                        else do;
                            treeValue5 = 0.05;
                        end;
                    end;
                    else do;
                        if (missing(feature_1) or feature_1 <= 0.68) then do;
                            treeValue5 = 0.03;
                        end;
                        else do;
                            treeValue5 = -0.02;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_13) or feature_13 <= 0.73) then do;
                        treeValue5 = 0.04;
                    end;
                    else do;
                        treeValue5 = -0.01;
                    end;
                end;
            end;
            else do;
                if (missing(feature_5) or feature_5 <= 1.18) then do;
                    if (missing(feature_0) or feature_0 <= 0.4) then do;
                        treeValue5 = 0.04;
                    end;
                    else do;
                        if (missing(feature_26) or feature_26 <= 0.89) then do;
                            treeValue5 = -0.04;
                        end;
                        else do;
                            treeValue5 = -0.01;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_0) or feature_0 <= 1.41) then do;
                        treeValue5 = 0.05;
                    end;
                    else do;
                        treeValue5 = -0.02;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1.49) then do;
        if (missing(feature_22) or feature_22 <= 1.01) then do;
            if (missing(feature_22) or feature_22 <= 0.88) then do;
                if (missing(feature_24) or feature_24 <= 1.05) then do;
                    treeValue5 = -0.03;
                end;
                else do;
                    if (missing(feature_23) or feature_23 <= 0.99) then do;
                        treeValue5 = -0.03;
                    end;
                    else do;
                        treeValue5 = 0.05;
                    end;
                end;
            end;
            else do;
                treeValue5 = -0.05;
            end;
        end;
        else do;
            treeValue5 = 0.01;
        end;
    end;
    else do;
        if (missing(feature_3) or feature_3 <= 1.83) then do;
            treeValue5 = -0.04;
        end;
        else do;
            treeValue5 = -0.09;
        end;
    end;
end;

/* Parsing tree 6*/
if (missing(feature_27) or feature_27 <= 0.9) then do;
    if (missing(feature_26) or feature_26 <= 0.81) then do;
        if (missing(feature_5) or feature_5 <= 1.34) then do;
            if (missing(feature_5) or feature_5 <= 0.7) then do;
                if (missing(feature_26) or feature_26 <= 0.77) then do;
                    if (missing(feature_24) or feature_24 <= 0.71) then do;
                        if (missing(feature_11) or feature_11 <= 0.58) then do;
                            treeValue6 = 0.0;
                        end;
                        else do;
                            treeValue6 = -0.05;
                        end;
                    end;
                    else do;
                        treeValue6 = -0.05;
                    end;
                end;
                else do;
                    treeValue6 = 0.0;
                end;
            end;
            else do;
                if (missing(feature_27) or feature_27 <= 0.76) then do;
                    treeValue6 = 0.0;
                end;
                else do;
                    treeValue6 = -0.03;
                end;
            end;
        end;
        else do;
            treeValue6 = 0.05;
        end;
    end;
    else do;
        if (missing(feature_5) or feature_5 <= 0.88) then do;
            if (missing(feature_22) or feature_22 <= 1.04) then do;
                if (missing(feature_0) or feature_0 <= 0.78) then do;
                    treeValue6 = -0.0;
                end;
                else do;
                    if (missing(feature_27) or feature_27 <= 0.84) then do;
                        treeValue6 = 0.03;
                    end;
                    else do;
                        if (missing(feature_26) or feature_26 <= 0.9) then do;
                            treeValue6 = -0.05;
                        end;
                        else do;
                            treeValue6 = 0.01;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue6 = 0.04;
            end;
        end;
        else do;
            treeValue6 = 0.04;
        end;
    end;
end;
else do;
    if (missing(feature_24) or feature_24 <= 1.03) then do;
        if (missing(feature_22) or feature_22 <= 1.05) then do;
            if (missing(feature_24) or feature_24 <= 0.73) then do;
                if (missing(feature_27) or feature_27 <= 1.09) then do;
                    treeValue6 = 0.01;
                end;
                else do;
                    treeValue6 = -0.06;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 0.79) then do;
                    treeValue6 = -0.02;
                end;
                else do;
                    treeValue6 = -0.07;
                end;
            end;
        end;
        else do;
            if (missing(feature_26) or feature_26 <= 1.37) then do;
                if (missing(feature_24) or feature_24 <= 0.79) then do;
                    treeValue6 = 0.04;
                end;
                else do;
                    treeValue6 = -0.0;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1.7) then do;
                    treeValue6 = -0.06;
                end;
                else do;
                    if (missing(feature_8) or feature_8 <= 1.63) then do;
                        treeValue6 = 0.02;
                    end;
                    else do;
                        treeValue6 = -0.06;
                    end;
                end;
            end;
        end;
    end;
    else do;
        if (missing(feature_27) or feature_27 <= 1.01) then do;
            if (missing(feature_9) or feature_9 <= 1.31) then do;
                treeValue6 = 0.01;
            end;
            else do;
                treeValue6 = 0.05;
            end;
        end;
        else do;
            if (missing(feature_24) or feature_24 <= 2.34) then do;
                if (missing(feature_22) or feature_22 <= 1.05) then do;
                    if (missing(feature_22) or feature_22 <= 0.74) then do;
                        treeValue6 = 0.03;
                    end;
                    else do;
                        if (missing(feature_13) or feature_13 <= 1.15) then do;
                            if (missing(feature_11) or feature_11 <= -0.97) then do;
                                treeValue6 = 0.03;
                            end;
                            else do;
                                treeValue6 = -0.02;
                            end;
                        end;
                        else do;
                            treeValue6 = -0.04;
                        end;
                    end;
                end;
                else do;
                    treeValue6 = 0.01;
                end;
            end;
            else do;
                if (missing(feature_1) or feature_1 <= 0.66) then do;
                    treeValue6 = -0.07;
                end;
                else do;
                    treeValue6 = 0.01;
                end;
            end;
        end;
    end;
end;

/* Parsing tree 7*/
if (missing(feature_25) or feature_25 <= 1.18) then do;
    if (missing(feature_25) or feature_25 <= 0.59) then do;
        if (missing(feature_5) or feature_5 <= 1.34) then do;
            if (missing(feature_27) or feature_27 <= 0.84) then do;
                if (missing(feature_0) or feature_0 <= 0.96) then do;
                    if (missing(feature_13) or feature_13 <= 1.24) then do;
                        treeValue7 = -0.04;
                    end;
                    else do;
                        treeValue7 = 0.04;
                    end;
                end;
                else do;
                    treeValue7 = 0.01;
                end;
            end;
            else do;
                treeValue7 = -0.04;
            end;
        end;
        else do;
            treeValue7 = 0.02;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.78) then do;
            if (missing(feature_5) or feature_5 <= 0.8) then do;
                treeValue7 = -0.03;
            end;
            else do;
                treeValue7 = 0.02;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.87) then do;
                    if (missing(feature_25) or feature_25 <= 0.95) then do;
                        if (missing(feature_27) or feature_27 <= 0.79) then do;
                            treeValue7 = 0.05;
                        end;
                        else do;
                            if (missing(feature_14) or feature_14 <= 0.77) then do;
                                treeValue7 = -0.02;
                            end;
                            else do;
                                treeValue7 = 0.04;
                            end;
                        end;
                    end;
                    else do;
                        treeValue7 = -0.03;
                    end;
                end;
                else do;
                    if (missing(feature_25) or feature_25 <= 1.0) then do;
                        if (missing(feature_25) or feature_25 <= 0.68) then do;
                            treeValue7 = 0.01;
                        end;
                        else do;
                            treeValue7 = 0.06;
                        end;
                    end;
                    else do;
                        treeValue7 = 0.02;
                    end;
                end;
            end;
            else do;
                if (missing(feature_0) or feature_0 <= 1.35) then do;
                    if (missing(feature_5) or feature_5 <= 0.87) then do;
                        if (missing(feature_25) or feature_25 <= 0.97) then do;
                            if (missing(feature_26) or feature_26 <= 0.99) then do;
                                if (missing(feature_3) or feature_3 <= 1.33) then do;
                                    treeValue7 = 0.01;
                                end;
                                else do;
                                    treeValue7 = -0.08;
                                end;
                            end;
                            else do;
                                treeValue7 = 0.02;
                            end;
                        end;
                        else do;
                            treeValue7 = -0.03;
                        end;
                    end;
                    else do;
                        if (missing(feature_1) or feature_1 <= -1.66) then do;
                            treeValue7 = -0.05;
                        end;
                        else do;
                            if (missing(feature_3) or feature_3 <= 2.62) then do;
                                treeValue7 = 0.03;
                            end;
                            else do;
                                treeValue7 = -0.04;
                            end;
                        end;
                    end;
                end;
                else do;
                    if (missing(feature_24) or feature_24 <= 0.94) then do;
                        treeValue7 = -0.06;
                    end;
                    else do;
                        if (missing(feature_24) or feature_24 <= 1.77) then do;
                            if (missing(feature_5) or feature_5 <= 1.03) then do;
                                if (missing(feature_9) or feature_9 <= 1.27) then do;
                                    treeValue7 = -0.04;
                                end;
                                else do;
                                    treeValue7 = 0.04;
                                end;
                            end;
                            else do;
                                treeValue7 = 0.03;
                            end;
                        end;
                        else do;
                            treeValue7 = -0.08;
                        end;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1.83) then do;
        if (missing(feature_25) or feature_25 <= 1.49) then do;
            if (missing(feature_5) or feature_5 <= 0.89) then do;
                if (missing(feature_23) or feature_23 <= 1.12) then do;
                    treeValue7 = -0.04;
                end;
                else do;
                    treeValue7 = 0.03;
                end;
            end;
            else do;
                treeValue7 = -0.0;
            end;
        end;
        else do;
            treeValue7 = -0.04;
        end;
    end;
    else do;
        treeValue7 = -0.07;
    end;
end;

/* Parsing tree 8*/
if (missing(feature_25) or feature_25 <= 1.07) then do;
    if (missing(feature_25) or feature_25 <= 0.67) then do;
        if (missing(feature_5) or feature_5 <= 1.34) then do;
            if (missing(feature_27) or feature_27 <= 0.84) then do;
                if (missing(feature_9) or feature_9 <= 1.28) then do;
                    if (missing(feature_3) or feature_3 <= 0.41) then do;
                        treeValue8 = 0.02;
                    end;
                    else do;
                        if (missing(feature_0) or feature_0 <= 1.58) then do;
                            if (missing(feature_13) or feature_13 <= 1.31) then do;
                                treeValue8 = -0.03;
                            end;
                            else do;
                                treeValue8 = 0.03;
                            end;
                        end;
                        else do;
                            treeValue8 = 0.03;
                        end;
                    end;
                end;
                else do;
                    treeValue8 = 0.05;
                end;
            end;
            else do;
                if (missing(feature_2) or feature_2 <= 1.1) then do;
                    if (missing(feature_2) or feature_2 <= 0.9) then do;
                        treeValue8 = -0.03;
                    end;
                    else do;
                        treeValue8 = 0.04;
                    end;
                end;
                else do;
                    treeValue8 = -0.07;
                end;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 1.0) then do;
                treeValue8 = 0.05;
            end;
            else do;
                treeValue8 = -0.01;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.78) then do;
            if (missing(feature_5) or feature_5 <= 0.8) then do;
                treeValue8 = -0.03;
            end;
            else do;
                treeValue8 = 0.02;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.87) then do;
                    if (missing(feature_27) or feature_27 <= 0.79) then do;
                        if (missing(feature_25) or feature_25 <= 0.95) then do;
                            treeValue8 = 0.05;
                        end;
                        else do;
                            treeValue8 = -0.01;
                        end;
                    end;
                    else do;
                        treeValue8 = -0.01;
                    end;
                end;
                else do;
                    treeValue8 = 0.05;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1.05) then do;
                    if (missing(feature_0) or feature_0 <= 1.0) then do;
                        if (missing(feature_18) or feature_18 <= 1.25) then do;
                            treeValue8 = 0.03;
                        end;
                        else do;
                            treeValue8 = -0.05;
                        end;
                    end;
                    else do;
                        if (missing(feature_27) or feature_27 <= 1.29) then do;
                            if (missing(feature_22) or feature_22 <= 0.97) then do;
                                treeValue8 = -0.02;
                            end;
                            else do;
                                treeValue8 = 0.03;
                            end;
                        end;
                        else do;
                            treeValue8 = -0.09;
                        end;
                    end;
                end;
                else do;
                    treeValue8 = 0.03;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_25) or feature_25 <= 1.49) then do;
        if (missing(feature_22) or feature_22 <= 1.01) then do;
            if (missing(feature_22) or feature_22 <= 0.87) then do;
                if (missing(feature_13) or feature_13 <= 0.86) then do;
                    treeValue8 = -0.03;
                end;
                else do;
                    if (missing(feature_9) or feature_9 <= 0.91) then do;
                        treeValue8 = -0.02;
                    end;
                    else do;
                        treeValue8 = 0.04;
                    end;
                end;
            end;
            else do;
                if (missing(feature_27) or feature_27 <= 0.89) then do;
                    if (missing(feature_5) or feature_5 <= 1.01) then do;
                        treeValue8 = -0.03;
                    end;
                    else do;
                        treeValue8 = 0.04;
                    end;
                end;
                else do;
                    treeValue8 = -0.07;
                end;
            end;
        end;
        else do;
            treeValue8 = 0.01;
        end;
    end;
    else do;
        if (missing(feature_3) or feature_3 <= 1.83) then do;
            treeValue8 = -0.04;
        end;
        else do;
            treeValue8 = -0.08;
        end;
    end;
end;

/* Parsing tree 9*/
if (missing(feature_25) or feature_25 <= 1.18) then do;
    if (missing(feature_25) or feature_25 <= 0.59) then do;
        if (missing(feature_13) or feature_13 <= 0.94) then do;
            if (missing(feature_9) or feature_9 <= 1.01) then do;
                treeValue9 = -0.03;
            end;
            else do;
                treeValue9 = 0.0;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.91) then do;
                if (missing(feature_25) or feature_25 <= 0.52) then do;
                    treeValue9 = 0.0;
                end;
                else do;
                    treeValue9 = 0.05;
                end;
            end;
            else do;
                treeValue9 = -0.03;
            end;
        end;
    end;
    else do;
        if (missing(feature_26) or feature_26 <= 0.78) then do;
            if (missing(feature_5) or feature_5 <= 0.8) then do;
                if (missing(feature_24) or feature_24 <= 0.72) then do;
                    treeValue9 = -0.0;
                end;
                else do;
                    if (missing(feature_19) or feature_19 <= -1.26) then do;
                        treeValue9 = 0.01;
                    end;
                    else do;
                        treeValue9 = -0.05;
                    end;
                end;
            end;
            else do;
                treeValue9 = 0.02;
            end;
        end;
        else do;
            if (missing(feature_27) or feature_27 <= 0.9) then do;
                if (missing(feature_26) or feature_26 <= 0.87) then do;
                    if (missing(feature_25) or feature_25 <= 0.95) then do;
                        if (missing(feature_27) or feature_27 <= 0.79) then do;
                            treeValue9 = 0.04;
                        end;
                        else do;
                            treeValue9 = -0.01;
                        end;
                    end;
                    else do;
                        treeValue9 = -0.03;
                    end;
                end;
                else do;
                    if (missing(feature_25) or feature_25 <= 1.0) then do;
                        if (missing(feature_25) or feature_25 <= 0.68) then do;
                            treeValue9 = 0.01;
                        end;
                        else do;
                            if (missing(feature_5) or feature_5 <= 0.48) then do;
                                treeValue9 = 0.01;
                            end;
                            else do;
                                treeValue9 = 0.06;
                            end;
                        end;
                    end;
                    else do;
                        treeValue9 = 0.02;
                    end;
                end;
            end;
            else do;
                if (missing(feature_22) or feature_22 <= 1.05) then do;
                    if (missing(feature_24) or feature_24 <= 1.0) then do;
                        if (missing(feature_24) or feature_24 <= 0.73) then do;
                            treeValue9 = 0.02;
                        end;
                        else do;
                            treeValue9 = -0.06;
                        end;
                    end;
                    else do;
                        treeValue9 = 0.01;
                    end;
                end;
                else do;
                    if (missing(feature_5) or feature_5 <= 1.24) then do;
                        treeValue9 = 0.01;
                    end;
                    else do;
                        treeValue9 = 0.04;
                    end;
                end;
            end;
        end;
    end;
end;
else do;
    if (missing(feature_3) or feature_3 <= 1.83) then do;
        if (missing(feature_24) or feature_24 <= 1.28) then do;
            if (missing(feature_25) or feature_25 <= 2.08) then do;
                if (missing(feature_24) or feature_24 <= 0.73) then do;
                    treeValue9 = 0.01;
                end;
                else do;
                    if (missing(feature_15) or feature_15 <= -1.57) then do;
                        treeValue9 = 0.03;
                    end;
                    else do;
                        if (missing(feature_22) or feature_22 <= 0.68) then do;
                            treeValue9 = 0.04;
                        end;
                        else do;
                            if (missing(feature_22) or feature_22 <= 0.97) then do;
                                treeValue9 = -0.05;
                            end;
                            else do;
                                treeValue9 = -0.02;
                            end;
                        end;
                    end;
                end;
            end;
            else do;
                treeValue9 = -0.08;
            end;
        end;
        else do;
            if (missing(feature_1) or feature_1 <= 1.18) then do;
                if (missing(feature_11) or feature_11 <= -0.97) then do;
                    treeValue9 = 0.03;
                end;
                else do;
                    treeValue9 = -0.02;
                end;
            end;
            else do;
                treeValue9 = 0.05;
            end;
        end;
    end;
    else do;
        treeValue9 = -0.07;
    end;
end;

/* Getting target probability */
treeValue = sum(treeValue0, treeValue1, treeValue2, treeValue3, treeValue4, treeValue5, treeValue6, treeValue7, treeValue8, treeValue9);
P_TARGET = 1 / (1 + exp(-treeValue));
